### ISSUE TITLE
New block type: Periodic boxes w/ optional icon

### ISSUE THREAD

**Issue by alexgleason** [ProjectTIER/projecttier.org#129]
Implement this design as a block type:

![Screenshot from 2019-12-02 12-45-23](https://user-images.githubusercontent.com/3639540/69985856-b12eb400-1501-11ea-914d-02b2df9cf41c.png)

Here's another variant of it without icons:

![Screenshot from 2019-12-02 12-45-48](https://user-images.githubusercontent.com/3639540/69985877-ba1f8580-1501-11ea-8259-6f4016144b70.png)

Related: #121

**Comment by marykatefain** [comment]
- Make link optional
- Create template
- style
