### ISSUE TITLE
Highlight block

### ISSUE THREAD

**Issue by alexgleason** [ProjectTIER/projecttier.org#173]
Have the ability to add a highlighted paragraph block. Will be used to give a summary, especially at the top of FolderPage and FilePages.

**Comment by marykatefain** [comment]
Can you link the relevant design, please?

**Comment by alexgleason** [comment]
It's really just a paragraph block with a tan background and some padding.

![Screenshot from 2020-02-29 16-20-26](https://user-images.githubusercontent.com/3639540/75615896-7263c680-5b0f-11ea-815b-1716f3326e19.png)

**Comment by marykatefain** [comment]
Thanks!
